name: deploy with helm

on:
  push:
    branches:
      - master

jobs:
  helm-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set Up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
        chmod 700 $HOME/.kube/config

    - name: Install Helm
      uses: azure/setup-helm@latest

    - name: Deploy with helm
      run: |
        helm upgrade --install my-release ./charts/my-app --namespace florin --create-namespace
        kubectl -n florin get all
        echo ${{ secrets.PW }}
        echo Hallo
