name: secret test 

on:
  push:
    branches:
      - main

jobs:
  secret-test:
    runs-on: ubuntu-latest

    steps:
    - name: ausgabe 
      run: |
        echo "HANS=${{secrets.SECRET}}" >> $GITHUB_ENV
    - name: ausgabe2
      run: env | grep "HANS" ;echo test
